In [68]:
import numpy as np
from random import shuffle


f = open('linear_train.txt', 'r')
data = []
for s in f:
    data.append(s)
shuffle(data)
words = []
answers = []
d = 0
for s in data:
    l = s.split(',')
    if (int(l[1]) == 0 and d % 5 == 0) or (int(l[1]) == 1):
        words.append(l[0])
        answers.append(int(l[1]))
    d += 1
k = 0
for i in answers:
    if i == 1:
        k += 1
print (k)
print(len(answers))
f.close()

10638
28835


In [3]:
from sklearn import cross_validation
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(words, answers, 
                                                                                     test_size = 0.3)

/home/cheshire/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
print ('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 20188 объектов 
Размер тестовой выборки: 8653 объектов


In [8]:
from sklearn import cross_validation, linear_model, metrics

In [542]:
words = []
answers = []
d = 0
for s in data:
    l = s.split(',')
    if (int(l[1]) == 0) or (int(l[1]) == 1):
        words.append(l[0])
        answers.append(int(l[1]))
    d += 1
k = 0
for i in answers:
    if i == 1:
        k += 1
print (k)
print(len(answers))

w_okon_1 = []
w_okon_fam_1 = []
i = 0
for w in words:
    if answers[i] == 1.0:
        w_okon_fam_1.append(w[-2:].lower())
    else:
        w_okon_1.append(w[-2:].lower())
    i += 1

10638
101408


In [544]:
sv = []
i = 0
for w in train_data:
    x = []
    if w[0].istitle():
        x.append(1.0)
        #print(w)
    else:
        x.append(0.0)
        #print(w)
    k = 0
    for c in w:
        if c in ['у','е','э','о','а','ы','я','и','э','У','Е','Э','О','А','Ы','Я','И','Э']:
            k+=1
    x.append(float(k))
    x.append(len(w))
        
    #if w[-2:].lower() in w_okon_fam_1:
     #   x.append(1.0)
    #else:
     #   x.append(0.0)
        
    a = 0    
    for s in w_okon_fam_1:
        for i in range(0,min(2, len(s), len(w))):
            if w[-i] == s[-i]:
                a += 1
    x.append(a)
    #if w[-2:].lower in w_okon_1:
     #   x.append(1.0)
    #else:
     #   x.append(0.0)

    
    sv.append(x)
    i += 1
    
sv_test = []
i = 0
for w in test_data:
    x = []
    if w[0].istitle():
        x.append(1.0)
        #print(w)
    else:
        x.append(0.0)
        #print(w)
    k = 0
    for c in w:
        if c in ['у','е','э','о','а','ы','я','и','э','У','Е','Э','О','А','Ы','Я','И','Э']:
            k+=1
    x.append(float(k))
    x.append(len(w))
        
        
    a = 0    
    for s in w_okon_fam_1:
        for i in range(0,min(2, len(s), len(w))):
            if w[-i] == s[-i]:
                a += 1
    x.append(a)

    #if w[-2:].lower() in w_okon_fam_1:
     #   x.append(1.0)
    #else:
     #   x.append(0.0)
    #if w[-2:].lower() in w_okon_1:
     #   x.append(1.0)
    #else:
     #   x.append(0.0)
    
    sv_test.append(x)
    i += 1

In [77]:
transformer = CountVectorizer(min_df=1, 
                              ngram_range=(3, 8), 
                              analyzer='char_wb', 
                              binary=True)

In [78]:
def lower(text):
    return text.lower()
import pandas as pnd
data = pnd.read_csv("sample11111.txt", 
                   sep=",", 
                   names=['Words', 'Answers'])

In [79]:

data['Words'] = data['Words'].apply(lower)
words = data['Words']
answers = data['Answers']
type(data['Words'])

pandas.core.series.Series

In [80]:

words = words.apply(lower)

In [81]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(words, answers, 
                                                                                     test_size = 0.3)

In [82]:
transformer = CountVectorizer(min_df=1, 
                              ngram_range=(3, 8), 
                              analyzer='char_wb', 
                              binary=True)
words = transformer.fit_transform(words)
classifier = linear_model.LogisticRegression(penalty='l2', 
                                C=3)
classifier.fit(words, answers)

LogisticRegression(C=3, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [83]:


test = pnd.read_csv('linear_test.txt', names=['Words'])
test['Words'] = test['Words'].apply(lower)
words = test['Words']
matrix = transformer.transform(words)

answers = pnd.read_csv('linear_ans_example.txt', 
                     sep=',', 
                     names=['Id', 'Answer'], 
                     header=0)
preds = classifier.predict_proba(matrix)
print(preds)



[[ 0.18749874  0.81250126]
 [ 0.69743153  0.30256847]
 [ 0.68669318  0.31330682]
 ..., 
 [ 0.91155743  0.08844257]
 [ 0.99872749  0.00127251]
 [ 0.9982309   0.0017691 ]]


In [84]:
len(classifier.coef_[0])

344125

In [545]:
ridge_classifier = linear_model.RidgeClassifier(random_state = 1)

In [546]:
ridge_classifier.fit(np.array(sv), train_labels)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
        max_iter=None, normalize=False, random_state=1, solver='auto',
        tol=0.001)

In [547]:
ridge_predictions = ridge_classifier.predict(sv_test)

In [548]:
metrics.accuracy_score(test_labels, ridge_predictions)

0.7587084828144891

In [549]:
ridge_classifier.coef_

array([[  9.09456352e-01,  -1.08080018e-01,  -7.87982762e-03,
          1.71443917e-04]])

In [550]:
ridge_classifier.intercept_ 

array([-0.53990171])

In [551]:
metrics.roc_auc_score(test_labels, ridge_predictions)

0.7614526195713609

In [552]:
log_regressor = linear_model.LogisticRegression(random_state = 0)

In [553]:
log_regressor.fit(sv, train_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [554]:
lr_predictions = log_regressor.predict(sv_test)

In [555]:
lr_proba_predictions = log_regressor.predict_proba(sv_test)

In [556]:
log_regressor.coef_

array([[  2.53344446e+00,  -3.51940821e-01,  -3.24461525e-02,
          5.03237125e-04]])

In [557]:
print (lr_proba_predictions)

[[ 0.66237791  0.33762209]
 [ 0.60308854  0.39691146]
 [ 0.32698497  0.67301503]
 ..., 
 [ 0.44657377  0.55342623]
 [ 0.91539188  0.08460812]
 [ 0.95824405  0.04175595]]


In [558]:
print (metrics.accuracy_score(test_labels, lr_predictions))

0.758245573429


In [559]:
metrics.roc_auc_score(test_labels, lr_predictions)

0.75351768002635366

In [523]:
f = open('linear_test.txt', 'r')
words_test = []
for s in f:
    words_test.append(s)  

sv_test = []
i = 0
for w in words_test:
    x = []
    if w[0].istitle():
        x.append(1.0)
        #print(w)
    else:
        x.append(0.0)
        #print(w)
    k = 0
    for c in w:
        if c in ['у','е','э','о','а','ы','я','и','э','У','Е','Э','О','А','Ы','Я','И','Э']:
            k+=1
    x.append(float(k))
    x.append(len(w))
    if w[-2:].lower() in w_okon_fam_1:
        x.append(1.0)
    else:
        x.append(0.0)
    if w[-2:].lower in w_okon_1:
        x.append(1.0)
    else:
        x.append(0.0)
    
    sv_test.append(x)
    i += 1
f.close()

In [524]:
lr_proba_predictions = log_regressor.predict_proba(sv_test)

In [525]:
lr_proba_predictions[0][1]

0.05061618138455766

In [85]:
fil = open('sample.txt', 'w')

In [86]:
fil.write('Id,Answer\n')

10

In [87]:
for i in range(len(preds)):
    fil.write(str(i) + ',' + str(preds[i][1]) + '\n')

In [88]:
fil.close()

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [74]:
fil = open('sample11111.txt', 'w')

In [75]:
for i in range(len(words)):
    fil.write(words[i] + ',' + str(answers[i]) + '\n')
fil.close()